name: flutter_starter_kit
description: "Application BDD directement accessible."
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.10.2
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  retrofit: ^4.9.1
  json_annotation: ^4.9.0
  flavor: ^2.0.0
  intl: ^0.20.2
  dio_mocked_responses: ^1.6.5+1
  flutter_svg: ^2.2.3
  characters: ^1.4.0
  dio_cache_interceptor: ^4.0.5
  hive: ^2.2.3
  freezed_annotation: ^3.1.0
  transparent_image: ^2.0.1
  go_router: ^17.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.9.1
  retrofit_generator: ^10.2.0
  json_serializable: ^6.11.2
  flutter_flavorizr: ^2.4.1
  bdd_widget_test: ^2.1.3
  freezed: ^3.2.3
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
